CREATE DATABASE customer_behaviour;

									-- ANSWERING IMPORTANT BUSINESS QUESTIONS -- 

-- Q1. What is the total revenue generated by male v/s female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM CustomerData
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM CustomerData
WHERE discount_applied = 'yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM CustomerData)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM CustomerData
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

-- Q4. Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM CustomerData
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type

-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, COUNT(customer_id) as total_customers,
AVG(purchase_amount) as avg_spend, SUM(purchase_amount) as total_revenue
FROM CustomerData
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased, 100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) as discount_rate
FROM CustomerData
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.
-- CTE (Common Table Expression)
WITH customer_type as(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM CustomerData)
SELECT customer_segment, count(*) as 'number_of_customers'
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts as (
SELECT category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM CustomerData
GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM CustomerData
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue
FROM CustomerData
GROUP BY age_group
ORDER BY total_revenue DESC;